chore: update release step
honestbank/terraform-gcp-gke pull request #93
Opened 2023-02-21 07:59 UTC by honestsubhadip

## Pull Request Submission Checklist

Please confirm that you have done the following before requesting reviews:

- [ ] I have confirmed that the PR type is appropriate for the change I am making according to the [Honest Pull Request and Commit Message Naming Conventions](https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c).
- [ ] I have typed an adequate description that explains **why** I am making this change.
- [ ] I have installed and run standard pre-commit hooks that lints and validates my code.

### Description

* update semantic release steps

2023-02-21 10:36 UTC, MXfive commented on .github/workflows/terratest.yaml
> +            @semantic-release/exec@6.0.2
Downgrade?

2023-02-21 10:42 UTC, honestsubhadip commented on .github/workflows/terratest.yaml
> +            @semantic-release/exec@6.0.2
ah my bad, copied from old repo.

2023-02-22 00:47 UTC, jai requested changes
incorrect PR type - please see https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c?pvs=4


Also, token permissions probably won't work - semantic release needs `content: write` and `pull-requests: write` - see https://github.com/honestbank/terraform-pagerduty-alerting/blob/main/.github/workflows/terratest.yaml

2023-02-22 03:02 UTC, honestsubhadip commented
> incorrect PR type - please see https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c?pvs=4
> 
> Also, token permissions probably won't work - semantic release needs `content: write` and `pull-requests: write` - see https://github.com/honestbank/terraform-pagerduty-alerting/blob/main/.github/workflows/terratest.yaml

@jai I see, thanks for the doc and pointing the permission.

2023-02-22 08:06 UTC, MXfive approved these changes

2023-02-22 10:54 UTC, jai commented on .github/workflows/terratest.yaml
> +  content: write
please check https://docs.github.com/en/actions/security-guides/automatic-token-authentication

2023-02-22 10:54 UTC, jai commented on .github/workflows/terratest.yaml
> +  content: write
```suggestion
  contents: write
```

2023-02-24 09:32 UTC, MXfive approved these changes

2023-04-21 08:47 UTC, closed without merging